language: python

jobs:
  # All three OSes agree about 'pip3'.  'python' points to Python 3.8 on Linux 
  # and Windows, but Python 2.7 on macOS.  'python3' is a 'command not found' 
  # error on Windows and 'py' works on Windows only.

  include:
    - name: "Python 3.8.0 on Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# In order for coverage to work, the package needs to be installed in editable/
# symlink mode.  Unfortunately, this means we can't use pip to install the 
# package (as of version 19.2), because pip cannot use `pyproject.toml` for 
# editable installs.  Instead it requires `setup.py`, which we don't have.  
# This means we need to use `flit` directly to install the package.

install:
    - pip3 install -U flit coverage pytest pytest-cov python-coveralls
    - flit install --symlink

script: 
    - pytest tests --cov stepwise

after_success:
    - coveralls
