language: python

jobs:
  # All three OSes agree about 'pip3'.  'python' points to Python 3.8 on Linux 
  # and Windows, but Python 2.7 on macOS.  'python3' is a 'command not found' 
  # error on Windows and 'py' works on Windows only.

  include:
    - name: "Python 3.8.0 on Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8.0 on macOS"
      os: osx
      before_install:
        - brew unlink python@2
        - brew unlink python
        - brew unlink python3
        - brew install python@3.8
        - brew link --overwrite --force python@3.8
        - python3 --version
        - python3 -m venv venv
        - source venv/bin/activate
        - pip3 install --upgrade pip
      language: shell       # 'language: python' is an error on Travis CI macOS

    # Remove Windows support until I can get a Windows machine to test with.  
    # It seems like a few things are just a bit off, e.g. how arguments are 
    # quoted by the shell, and I just think it'll be too much of a pain to 
    # figure out by pushing to Travis CI over and over.

    #- name: "Python 3.8.0 on Windows"
    #  os: windows           # Windows 10.0.17134 N/A Build 17134
    #  language: shell       # 'language: python' is an error on Travis CI Windows
    #  before_install:
    #    - choco install python --version 3.8.0
    #    - python -m pip install --upgrade pip
    #  env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# In order for coverage to work, the package needs to be installed in editable/
# symlink mode.  Unfortunately, this means we can't use pip to install the 
# package (as of version 19.2), because pip cannot use `pyproject.toml` for 
# editable installs.  Instead it requires `setup.py`, which we don't have.  
# This means we need to use `flit` directly to install the package.

install:
  - pip3 install -U flit coverage pytest pytest-cov coveralls
  - flit install --symlink

  # Required for the tests that call `git` and expected certain output.
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis-ci@example.com"

script: 
  - pytest tests --cov stepwise

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "U4pA9MLYI067GtRlA1OW/QZVvmX3OAVgYx0r1vX0YUyz8+sFWLhuTugshe/13NYG2ticOkv+8U6TMZMH6ULmV0mL29heSMIvUcagGgbrlHqZxVvRBiciO3NSvs6lvbqi18zte3TfYmetUFCmt07n3H1Udg3vWyXv1102mV4JdVFY7js5J/MJ05oCMaGOcBUt9Zpm9p9U7wTeUVkSAy2tQaYBRt0sHQQXWENWq2gb4ag6VOfRxldgQF5NEJDlzU/+9/pLQAM3Y9Eto5nmMAIhHj6SxteyN8jcdqQkAfMBCJd2nJVDRf6YPdQ/pMKdOPawCRjQBmesyoMhuZ6FxB1E3Xw+EfrdudJ+NdZp9F28YGl9RL9kB+Ejoz5mH1G2NQRg1kkOUuHzwrhEXZAk0+Ep3Lm5DXHg1/rE/2vJGEENHc75ECpiFjW8pLMISAEu79KdA2M45Lctb093QLK6TxgL9jSzYg1N7GQ9+u5vyZWtd2TA5y881z7Z9PQGv5BUiJXBlEoKjasekhLyPTIGkycPVe8By658/xCwAJQMEYLFy8HUjc0aoFaSTzHaa6s0oaLPRmZgSfYSJXNdk+3ssiFsXnX/rxLKI6QzWuhGv1tU1SQCYsNFpJw/lolkwIf/3Jx0nUs6FhHO8O49WNpCuLPn6OOROQwMjpWAxQlgPZ4jr/0="
  on:
    tags: true
