name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Run pytest

    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - '3.10'
        os: 
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[tests]'
          # Required for the tests that call `git` and expected certain output.
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@example.com"
      - name: Run test suite
        run: |
          pytest tests --cov stepwise
      - name: Report test coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          coveralls
